// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB023dF5ijc4mMzFTmBbTAX4SHrxD-rqsM',
    appId: '1:724222720573:web:015b521c74db6f1913c854',
    messagingSenderId: '724222720573',
    projectId: 'tumbuh-iman',
    authDomain: 'tumbuh-iman.firebaseapp.com',
    storageBucket: 'tumbuh-iman.firebasestorage.app',
    measurementId: 'G-KSG4GR80Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoDK45xKisYAlCMl6-yGR37CKubdagCgM',
    appId: '1:724222720573:android:3d4093353dee7e2a13c854',
    messagingSenderId: '724222720573',
    projectId: 'tumbuh-iman',
    storageBucket: 'tumbuh-iman.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz8QjIUYG5uZ90E_m6bNt_SMWbko5opG4',
    appId: '1:724222720573:ios:96e73737310f579213c854',
    messagingSenderId: '724222720573',
    projectId: 'tumbuh-iman',
    storageBucket: 'tumbuh-iman.firebasestorage.app',
    iosBundleId: 'com.fghilmany.tumbuhiman',
  );
}
